//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaPOSEntities : DbContext
    {
        public PizzaPOSEntities()
            : base("name=PizzaPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExtraTopping> ExtraToppings { get; set; }
        public virtual DbSet<InventoryItem> InventoryItems { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderItemTopping> OrderItemToppings { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PizzaCategory> PizzaCategories { get; set; }
        public virtual DbSet<PizzaMaster> PizzaMasters { get; set; }
        public virtual DbSet<PizzaPrice> PizzaPrices { get; set; }
        public virtual DbSet<PizzaSize> PizzaSizes { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<StockTransaction> StockTransactions { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
