//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemTopping
    {
        public int OrderItemToppingId { get; set; }
        public int OrderItemId { get; set; }
        public int ToppingId { get; set; }
        public decimal Price { get; set; }
    
        public virtual ExtraTopping ExtraTopping { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
