//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipeId { get; set; }
        public int PizzaId { get; set; }
        public int PizzaSizeId { get; set; }
        public int ItemId { get; set; }
        public decimal QuantityRequired { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual PizzaMaster PizzaMaster { get; set; }
        public virtual PizzaSize PizzaSize { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
